# Generated by Django 6.0.1 on 2026-02-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_shorturl_time_date_created_shorturl_clicks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='clicks',
            new_name='click_count',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='created_at',
            new_name='time_date_created',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='user',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shorturls', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
